- id: turn_off_master_bathroom_exhaust_fan_811ad634
  alias: Turn off Master Bathroom Exhaust Fan after 20 minutes
  trigger:
    - platform: state
      entity_id: switch.master_bathroom_shower_lights
      to: "off"
  condition:
    - condition: state
      entity_id: switch.master_bathroom_exhaust_fan
      state: "on"
  action:
    - service: tts.google_translate_say
      data:
        entity_id: media_player.nestmini2857
        message: "The exhaust fan will turn off in 20 minutes"
        cache: true
    - delay:
        hours: 0
        minutes: 20
        seconds: 0
        milliseconds: 0
    - type: turn_off
      device_id: 9f0dd6746f96ab7258b9858534129788
      entity_id: switch.master_bathroom_exhaust_fan
      domain: switch
  mode: restart

- id: turn_on_master_bedroom_closet_lights_d88e4d88
  alias: Turn on Master Bedroom Closet lights when Door Opened
  trigger:
    - type: opened
      platform: device
      device_id: 2e2832a09a9845331491d0ad85f97f68
      entity_id: binary_sensor.master_bedroom_closet_door_sensor
      domain: binary_sensor
  condition: []
  action:
    - type: turn_on
      device_id: 2e2832a09a9845331491d0ad85f97f68
      entity_id: light.master_bedroom_closet_light
      domain: light
  mode: single

- id: turn_off_master_bedroom_closet_lights_1094ceb2
  alias: Turn off Master Bedroom Closet lights when Door Closed
  trigger:
    - type: not_opened
      platform: device
      device_id: 2e2832a09a9845331491d0ad85f97f68
      entity_id: binary_sensor.master_bedroom_closet_door_sensor
      domain: binary_sensor
  condition: []
  action:
    - type: turn_off
      device_id: 2e2832a09a9845331491d0ad85f97f68
      entity_id: light.master_bedroom_closet_light
      domain: light
  mode: single

- id: turn_off_master_bedroom_closet_lights_1b3f7f25
  alias: Turn off Master Bedroom Closet lights after 5 minutes
  trigger:
    - platform: state
      device_id: 2e2832a09a9845331491d0ad85f97f68
      entity_id: light.master_bedroom_closet_light
      to: "on"
  condition: []
  action:
    - delay:
        hours: 0
        minutes: 5
        seconds: 0
        milliseconds: 0
    - type: turn_ff
      device_id: 2e2832a09a9845331491d0ad85f97f68
      entity_id: light.master_bedroom_closet_light
      domain: light
  mode: single

- id: update_openuv_data_e07a4339
  alias: Update OpenUV data
  trigger:
    - platform: time_pattern
      minutes: "/30"
  condition:
    - condition: and
      conditions:
        - condition: sun
          after: sunrise
          after_offset: "1:00:00"
        - condition: sun
          before: sunset
          before_offset: "1:00:00"
  action:
    - service: openuv.update_data
  mode: single
