---
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  auth_mfa_modules:
    - type: totp
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24

recorder:
  db_url: !secret postgres_url
  purge_keep_days: 30

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

light groups: !include light-groups.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.10

nest:
  client_id: >-
    308745043070-6n8jqq3ik40jqvva5v2h6k00ikvjl5pk.apps.googleusercontent.com
  client_secret: !secret nest_client_secret
  project_id: e22f54f1-45ef-4596-9858-ffaa8129fa94
  subscriber_id: projects/home-assistant-334403/subscriptions/home
