---
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  auth_mfa_modules:
    - type: totp
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24

recorder:
  db_url: !secret postgres_url
  purge_keep_days: 30

# Text to speech
tts:
  - platform: google_translate
    base_url: http://192.168.1.10:8123

input_boolean: !include inputs/boolean.yaml
group: !include groups.yaml
automation managed: !include_dir_merge_list automations/
automation unamanged: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include_dir_merge_list template/
timer: !include timers.yaml

light groups: !include light-groups.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.10
    - 172.19.0.0/16
