---
name: Home Assistant
on:  # yamllint disable-line rule:truthy
  push:
  schedule:
    - cron: "0 6 * * 0"
jobs:
  lint:
    name: YAML Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out configuration from GitHub
        uses: actions/checkout@v2
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: "."
  check_config:
    name: Core Configuration Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [stable, beta, dev]
    steps:
      - name: Check out configuration from GitHub
        uses: actions/checkout@v2
      - name: Run Home Assistant Configuration Check
        uses: frenck/action-home-assistant@v1
        with:
          path: "./"
          secrets: secrets.test.yaml
          version: ${{ matrix.tag }}
