---
name: Home Assistant
on: [push]
jobs:
  lint:
    name: YAML Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out configuration from GitHub
        uses: actions/checkout@v2
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: "."
  format:
    name: YAML Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Check out configuration from GitHub
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Format YAML files
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: "--write ./**/*.{yaml,yml}"
          commit_message: "Format YAML code"
          commit_description: >
            Performed by GitHub Actions
            action: creyD/prettier_action
            definition: .github/workflows/ci.yml
